[package]
name = "tab-kat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
lazy_static = "1.4.0"
log = "0.4.17"
simple_logger = "4.0.0"
sqlite = "0.30.4"
tiny_http = "0.12.0"
